### PR TITLE
try to fix densepose node #139

### PR DESCRIPTION
**Pull request by Layer-norm**
Fix issue #139 
I tried the fixed models, but those seems lack of some thing. so I add these Functions and Classes from your colab notebook. 
Besides, if the input image is big enough, the fixed model will return strang results below which I had no idea to fix it
fixedmodelbug
So I use your colab notebook generated two models and uploaded them into [huggingface](https://huggingface.co/LayerNorm/DensePose-TorchScript-with-hint-image).
I don`t kown what happened  exactlly but they seems work now.

mymodels

### CODE REVIEW

**Comment by Fannovel16** [comment]
Oh I didn't check this commit

**Comment by Fannovel16** [comment]
> Besides, if the input image is big enough, the fixed model will return strang results below which I had no idea to fix it
TorchScript tracing is kinda dumb when the resolution is different than traced input's resolution

**Comment by Fannovel16** [comment]
Can you do a comparision between my new one and yours? I don't have time to test now.

**Comment by Layer-norm** [comment]
I think this is the difference，I added height and width in the inference_func.
```
def inference_func(model, image):
    with torch.no_grad():  # https://github.com/sphinx-doc/sphinx/issues/4258

        _, height, width = image.shape

        inputs = {"image": image, "height": height, "width": width}

        outputs = predictor.model([inputs])[0]["instances"]

        pred_densepose = outputs.get("pred_densepose") if outputs.has("pred_densepose") else None

        return (
            outputs.get("pred_boxes").tensor.cpu(), #pred_boxes_XYXY
            pred_densepose.coarse_segm if pred_densepose else torch.Tensor([-1]), #coarse_segm
            pred_densepose.fine_segm if pred_densepose else torch.Tensor([-1]), #fine_segm
            pred_densepose.u if pred_densepose else torch.Tensor([-1]), #u
            pred_densepose.v if pred_densepose else torch.Tensor([-1]), #v
        )

```

**Comment by Layer-norm** [comment]
Besides, my torchscript models can works on your code, and your model can also works on my code. 
Small resolution can give better resolut. 
Here are the results. 
your model with your code（512）:
youryour
your model with my code（512）:
yourmy
my model with your code (512):
myyour
my model with my code (512 and 1024):
mymy

**Comment by Layer-norm** [comment]
It's too late yesterday and I'll try to solve conflicts today.

**Comment by Fannovel16** [comment]
@Layer-norm You don't need to do that. I will revert my commit

**Comment by Fannovel16** [comment]
Oops. My revert commit's message is a bit ambiguous 😅

**Comment by Fannovel16** [comment]
Some users from banodoco Discord server says that there is a serve lagging on web browsers when previewing the the result from both your DensePose and mine.

**Pull request merged**
